ci-cd-pipeline changes 1 added

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -21,9 +21,17 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y docker-compose
 
+      - name: Verify Docker Compose File Exists
+        run: |
+          ls -la
+          if [ ! -f "docker-compose.yml" ]; then
+            echo "Error: docker-compose.yml not found in root directory!"
+            exit 1
+          fi
+
       - name: Build Docker images using Docker Compose
         run: |
-          docker-compose -f docker-compose.yaml build
+          docker-compose -f docker-compose.yml build
 
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
